version: '3.8'

services:
    db:
        container_name: database
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root-test
            MYSQL_PASSWORD: root
            MYSQL_USER: cms-user
            MYSQL_DATABASE: test_cms
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
    
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8100:80

    web:
        container_name: cms
        build: .
        ports:
            - 8000:80

volumes:
    dbdata: